### ISSUE TITLE
Isn't the `handler` parameter  that should be unsubscribe?

### ISSUE THREAD

**Issue by lijsh** [egoist/eventstop#3]
[https://github.com/egoist/eventstop/blob/master/src/index.js#L9](https://github.com/egoist/eventstop/blob/master/src/index.js#L9)
Isn't the `handler` that should be unsubscribe, not the `fn`? because it's the `handler` that pushed to the `this.events[event]`.

but the `once` test is passed, whice is the most puzzling part.

**Comment by egoist** [comment]
fixed with refactor in `v2.0`
